experiment_name: 'Bi-EDL_Finetuning'
project: 'Bi-EDL_Finetuning_CARZero'
name: 'Bi-EDL_Finetuning_CARZero_Chest14'
phase: 'pretrain_llm_dqn_wo_self_atten_mlp_gl'

freeze:
    image: false
    text: false
    fusion: false

peft:
    enabled: false
    r: 8
    alpha: 32
    dropout: 0.1
    adaptor_name: 'lora'

lightning:
    trainer:
        gpus: 1
        max_epochs: 1000
        distributed_backend: 'ddp'
        gradient_clip_val: 0.25
        lr: 0.00001
        precision: '16-mixed'
        reload_dataloaders_every_epoch: True 
        val_check_interval: 1.0
    checkpoint_callback: 
        monitor: 'val_loss'
        dirpath: './data/ckpt'
        save_last: true 
        mode: min
        save_top_k: 1
    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 100
        verbose: False
        mode: 'min'
    logger:
        logger_type: 'CSVLogger'  #WandbLogger
        save_dir: './data/CSV'

model:
    norm: false
    CARZero: 
        local_loss_weight: 1.0
        global_loss_weight: 1.0
        ce_loss_weight: 1.0
        temp1: 4.0
        temp2: 5.0
        temp3: 10.0
        multi: true
        single_path: true
        shared_fusion: false
    vision:   
        model_name: 'vit_b_16'
        base: 'transformer'  
        freeze_cnn: false
        pretrained: true

    text:  
        bert_type: "Laihaoran/BioClinicalMPBERT"
        last_n_layers: 4
        aggregate_method: 'sum'
        norm: false
        embedding_dim: 768
        freeze_bert: false
        agg_tokens: true
    fusion:
        d_model: 768
        H: 4
        N: 4
        dropout: 0.1
        state_prob: 1
        class_num: 1
        decoder_number_layer: 4
        i2t_average_attn_weights: true
        t2i_average_attn_weights: true
# 
data: 
    dataset: pretrain_xh
    text: 
      word_num: 97
      captions_per_image: 5
      full_report: false
      generate_mcq2: false
      no_hyb: true
    image:
        imsize: 256
    fewshot:
        enabled: false
        ratio: 0.01

transforms: 
    norm: 'CXR_MAE'
    random_crop:
        crop_size: 224
    random_horizontal_flip: 0.3
    random_affine:
        degrees: 30
        translate: [0.1, 0.1]
        scale: [0.9, 1.1]
    color_jitter:
        bightness: [0.8, 1.2]
        contrast: [0.8, 1.2]

train: 
    update_interval: 1000
    batch_size: 64
    num_workers: 6
    nvis: 4
    rand_vis: false 
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 1
    seed: 14
    weight: 0.5
    lam: 15
    edl_weight: 0.1
test : 
    batch_size: 256
    num_workers: 6